machine: archlinux-personal-workstation
platform: archlinux

# Installation
system_packages: true
flatpak: true

go: true
go_tools:
  - task
  - cheat
  - terraform-docs
  - gum
  - lazydocker
  - actionlint
  - goose
  - gofumpt
  - golangci-lint
  - gdu
  - sesh
  - toolbox
  - sops

github_releases:
  - fzf
  - neovim
  - lazygit
  - yazi
  - glow
  - duf
  - tflint
  - terraformer
  - terrascan
  - trivy
  - zk
  - shellcheck
  - hadolint
  - tree-sitter
  - just

custom_installers:
  - bats
  - awscli
  - claude-code
  - terraform-ls
  - theme
  - font

rust: true
cargo_packages: [bat, fd-find, eza, zoxide, git-delta, oxker, broot, webviewrs]

nvm: true
npm_globals: true
uv: true
uv_tools: true
git_uv_tools: true
tenv: true

shell_plugins: true
tmux_plugins: true
nvim_plugins: true
configure_zsh: true
