machine: wsl-work-workstation
platform: wsl

# Installation
system_packages: true

go_tools:
  - task
  - cheat
  - terraform-docs
  - gum
  - lazydocker
  - actionlint
  # - goose
  # - gofumpt
  # - golangci-lint
  - gdu
  - sesh
  - toolbox

github_releases:
  - fzf
  - neovim
  - lazygit
  - yazi
  - glow
  - duf
  - tflint
  - terraformer
  - terrascan
  - trivy
  - zk
  - shellcheck
  - hadolint
  - tree-sitter
  - just
  - win32yank
  - tenv

custom_installers:
  # - bats
  - awscli
  - claude-code
  - terraform-ls
  - theme
  - font

cargo_packages: [bat, fd-find, eza, zoxide, git-delta, oxker, broot]

npm_globals:
  - typescript-language-server
  - typescript
  - bash-language-server
  - yaml-language-server
  - vscode-langservers-extracted
  - gh-actions-language-server
  - "@taplo/cli"
  - eslint
  - prettier
  - markdownlint-cli
  - sass

uv_tools:
  - ruff
  - mypy
  - basedpyright
  - codespell
  - sqlfluff
  - djlint
  - yq
  - keymap-drawer
  - nbpreview
  - numpy
  - pre-commit
  - git-filter-repo
  - tldr

git_uv_tools:
  - refcheck
  - indy

shell_plugins: true
tmux_plugins: true
nvim_plugins: true
configure_zsh: true
