version: '3'

vars:
  DOTFILES_DIR:
    sh: pwd
  PLATFORM:
    sh: |
      if [ -f "$HOME/.env" ]; then
        source "$HOME/.env" && echo "$PLATFORM"
      elif [ "$(uname)" = "Darwin" ]; then
        echo "macos"
      else
        echo "linux"
      fi

includes:
  brew:
    taskfile: ./management/taskfiles/brew.yml
    optional: true
  nvm:
    taskfile: ./management/taskfiles/nvm.yml
    optional: true
  npm-global:
    taskfile: ./management/taskfiles/npm-global.yml
    optional: true
  uv-tools:
    taskfile: ./management/taskfiles/uv-tools.yml
    optional: true
  shell-plugins:
    taskfile: ./management/taskfiles/shell-plugins.yml
    optional: true
  symlinks:
    taskfile: ./management/taskfiles/symlinks.yml
    optional: true
  docs:
    taskfile: ./management/taskfiles/docs.yml
    optional: true
  macos:
    taskfile: ./management/taskfiles/macos.yml
    optional: true
  wsl:
    taskfile: ./management/taskfiles/wsl.yml
    optional: true
  arch:
    taskfile: ./management/taskfiles/arch.yml
    optional: true

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Auto-detect platform and install dotfiles
    silent: true
    cmds:
      - |
        case "{{.PLATFORM}}" in
          macos)
            echo "Detected macOS platform"
            task install-macos
            ;;
          linux)
            if grep -q "Microsoft" /proc/version 2>/dev/null; then
              echo "Detected WSL Ubuntu"
              task install-wsl
            elif [ -f /etc/arch-release ]; then
              echo "Detected Arch Linux"
              task install-arch
            else
              echo "Unknown Linux distribution"
              exit 1
            fi
            ;;
          *)
            echo "Unknown platform: {{.PLATFORM}}"
            exit 1
            ;;
        esac

  # ================================================================
  # COMMON INSTALLATION PHASES (2-9)
  # ================================================================
  # Internal task used by all platform install tasks
  # Handles universal installation steps that are the same across platforms

  install-common-phases:
    internal: true
    silent: true
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "$HOME/dotfiles/platforms/common/shell/formatting.sh"
        print_header "Phase 2 - GitHub Release Tools" "cyan"
        bash management/scripts/install-go.sh
        bash management/scripts/install-fzf.sh
        bash management/scripts/install-neovim.sh
        bash management/scripts/install-lazygit.sh
        bash management/scripts/install-yazi.sh
        echo ""
        print_header "Phase 3 - Rust/Cargo Tools" "cyan"
        bash management/scripts/install-rust.sh
        bash management/scripts/install-cargo-binstall.sh
        bash management/scripts/install-cargo-tools.sh
        echo ""
        print_header "Phase 4 - Language Package Managers" "cyan"
      - task: nvm:install
      - task: npm-global:install
      - bash management/scripts/install-uv.sh
      - task: uv-tools:install
      - |
        echo ""
        print_header "Phase 5 - Shell Configuration" "cyan"
      - task: shell-plugins:install
      - |
        echo ""
        print_header "Phase 6 - Custom Go Applications" "cyan"
        cd apps/common/sess && PATH="/usr/local/go/bin:$PATH" task install
        cd apps/common/toolbox && PATH="/usr/local/go/bin:$PATH" task install
        echo ""
        print_header "Phase 7 - Symlinking Dotfiles" "cyan"
      - task: symlinks:link
      - |
        echo ""
        print_header "Phase 8 - Theme System" "cyan"
        source "$HOME/.cargo/env" && tinty install
        source "$HOME/.cargo/env" && tinty sync
        echo ""
        print_header "Phase 9 - Plugin Installation" "cyan"
        bash management/scripts/install-tpm.sh
        bash management/scripts/install-tmux-plugins.sh
        bash management/scripts/install-nvim-plugins.sh

  # ================================================================
  # PLATFORM-SPECIFIC INSTALLATION
  # ================================================================

  install-macos:
    desc: Full macOS installation
    silent: true
    cmds:
      - |
        echo "Starting macOS dotfiles installation..."
        echo ""
        export TERM=${TERM:-xterm}
        source "$HOME/dotfiles/platforms/common/shell/formatting.sh"
        print_header "Phase 1 - System Tools (Homebrew)" "cyan"
      - task: macos:install-homebrew
      - task: macos:install-xcode-tools
      - task: brew:install
      - echo ""
      - task: install-common-phases
      - |
        echo ""
        print_header_success "macOS Installation Complete!"
        echo ""

  install-wsl:
    desc: Full WSL Ubuntu installation
    silent: true
    cmds:
      - |
        echo "Starting WSL Ubuntu dotfiles installation..."
        echo ""
        export TERM=${TERM:-xterm}
        source "$HOME/dotfiles/platforms/common/shell/formatting.sh"
        print_header "Phase 1 - System Packages (apt)" "cyan"
      - task: wsl:install-packages
      - echo ""
      - task: install-common-phases
      - |
        echo ""
        print_header_success "WSL Ubuntu Installation Complete!"
        echo ""

  install-arch:
    desc: Full Arch Linux installation
    silent: true
    cmds:
      - |
        echo "Starting Arch Linux dotfiles installation..."
        echo ""
        export TERM=${TERM:-xterm}
        source "$HOME/dotfiles/platforms/common/shell/formatting.sh"
        print_header "Phase 1 - System Packages (pacman)" "cyan"
      - task: arch:install-packages
      - echo ""
      - task: install-common-phases
      - |
        echo ""
        print_header_success "Arch Linux Installation Complete!"
        echo ""
