version: '3'

vars:
  DOTFILES_DIR:
    sh: pwd

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ================================================================
  # SYMLINKS MANAGEMENT
  # ================================================================

  symlinks:link:
    desc: Create symlinks from dotfiles to home directory
    silent: true
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "{{.DOTFILES_DIR}}/platforms/common/.local/shell/formatting.sh"
        print_section "Creating symlinks" "cyan"

        # Detect platform (check env var first, then system detection)
        if [ -n "${PLATFORM:-}" ]; then
          # PLATFORM already set (e.g., from ~/.env in Docker tests)
          :
        elif [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        elif [ -f /etc/lsb-release ] && grep -q "Ubuntu" /etc/lsb-release 2>/dev/null; then
          PLATFORM="ubuntu"
        else
          echo "Unknown platform"
          exit 1
        fi

        # Link common first (base layer), then platform (overlay)
        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks link common
        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks link "$PLATFORM"

  symlinks:relink:
    desc: Remove all symlinks and recreate them (idempotent)
    silent: true
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "{{.DOTFILES_DIR}}/platforms/common/.local/shell/formatting.sh"
        print_section "Relinking symlinks" "cyan"

        # Detect platform (check env var first, then system detection)
        if [ -n "${PLATFORM:-}" ]; then
          # PLATFORM already set (e.g., from ~/.env in Docker tests)
          :
        elif [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        elif [ -f /etc/lsb-release ] && grep -q "Ubuntu" /etc/lsb-release 2>/dev/null; then
          PLATFORM="ubuntu"
        else
          echo "Unknown platform"
          exit 1
        fi

        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks relink "$PLATFORM"

  symlinks:check:
    desc: Verify all symlinks are correct
    silent: true
    cmds:
      - cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks check

  symlinks:show:
    desc: Show all configured symlinks
    silent: true
    cmds:
      - cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks show

  symlinks:unlink:
    desc: Remove all symlinks
    silent: true
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "{{.DOTFILES_DIR}}/platforms/common/.local/shell/formatting.sh"
        print_section "Removing symlinks" "cyan"

        # Detect platform (check env var first, then system detection)
        if [ -n "${PLATFORM:-}" ]; then
          # PLATFORM already set (e.g., from ~/.env in Docker tests)
          :
        elif [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        elif [ -f /etc/lsb-release ] && grep -q "Ubuntu" /etc/lsb-release 2>/dev/null; then
          PLATFORM="ubuntu"
        else
          echo "Unknown platform"
          exit 1
        fi

        # Unlink platform first (overlay), then common (base layer)
        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks unlink "$PLATFORM"
        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks unlink common

  # ================================================================
  # SHELL BUILD
  # ================================================================

  shell:build:
    desc: Build shell functions.sh and aliases.sh from machine manifest
    silent: true
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "{{.DOTFILES_DIR}}/platforms/common/.local/shell/formatting.sh"
        print_section "Building shell files" "cyan"

        # Determine machine manifest
        MACHINE="${MACHINE:-}"
        if [ -z "$MACHINE" ]; then
          # Auto-detect from PLATFORM
          if [ -n "${PLATFORM:-}" ]; then
            :
          elif [ "$(uname)" = "Darwin" ]; then
            PLATFORM="macos"
          elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
            PLATFORM="wsl"
          elif [ -f /etc/arch-release ]; then
            PLATFORM="arch"
          elif [ -f /etc/lsb-release ] && grep -q "Ubuntu" /etc/lsb-release 2>/dev/null; then
            PLATFORM="ubuntu"
          else
            echo "Cannot detect platform. Set MACHINE or PLATFORM."
            exit 1
          fi

          # Map platform to default machine manifest
          case "$PLATFORM" in
            macos) MACHINE="macos-personal-workstation" ;;
            arch)  MACHINE="arch-personal-workstation" ;;
            wsl)   MACHINE="wsl-work-workstation" ;;
            ubuntu) MACHINE="ubuntu-lxc-server" ;;
            *) echo "Unknown platform: $PLATFORM"; exit 1 ;;
          esac
        fi

        bash "{{.DOTFILES_DIR}}/management/shell/build-shell.sh" \
          "{{.DOTFILES_DIR}}/management/machines/${MACHINE}.yml"

        # Sync to Windows Git Bash (only runs in WSL, skips otherwise)
        bash "{{.DOTFILES_DIR}}/management/shell/sync-windows-shell.sh" || true

  # ================================================================
  # TESTING
  # ================================================================

  test:
    desc: Run all BATS tests
    cmds:
      - bats tests/install/integration/*.bats

  test:unit:
    desc: Run unit tests
    cmds:
      - echo "No unit tests yet"

  test:integration:
    desc: Run integration tests
    cmds:
      - bats tests/install/integration/*.bats

  test:watch:
    desc: Run tests on file changes (requires entr)
    cmds:
      - |
        if ! command -v entr >/dev/null 2>&1; then
          echo "entr not installed. Install with: brew install entr (macOS) or apt install entr (Linux)"
          exit 1
        fi
        find tests -name '*.bats' | entr -c bats tests/install/integration/*.bats

  # ================================================================
  # DOCUMENTATION
  # ================================================================

  docs:serve:
    desc: Serve documentation site locally
    cmds:
      - cd docs && mkdocs serve

  docs:build:
    desc: Build documentation site
    cmds:
      - cd docs && mkdocs build

  docs:deploy:
    desc: Deploy documentation to GitHub Pages
    cmds:
      - cd docs && mkdocs gh-deploy --force

  # ================================================================
  # WINDOWS (WSL only)
  # ================================================================

  windows:setup:
    desc: One-time Windows Git Bash setup (run from WSL)
    cmds:
      - bash "{{.DOTFILES_DIR}}/management/shell/setup-windows.sh"
