version: '3'

vars:
  DOTFILES_DIR:
    sh: pwd

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ================================================================
  # INSTALLATION
  # ================================================================

  install:
    desc: Install dotfiles (delegates to install.sh)
    cmds:
      - bash install.sh {{.CLI_ARGS}}

  # ================================================================
  # FONT INSTALLATION
  # ================================================================

  fonts:download:
    desc: Download coding fonts from GitHub releases
    cmds:
      - bash management/common/install/fonts/download.sh {{.CLI_ARGS}}

  fonts:install:
    desc: Install downloaded fonts to system font directory
    cmds:
      - bash management/common/install/fonts/install.sh {{.CLI_ARGS}}

  # ================================================================
  # SYMLINKS MANAGEMENT
  # ================================================================

  symlinks:link:
    desc: Create symlinks from dotfiles to home directory
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "{{.DOTFILES_DIR}}/platforms/common/shell/formatting.sh"
        print_section "Creating symlinks" "cyan"

        # Detect platform
        if [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        else
          echo "Unknown platform"
          exit 1
        fi

        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks link "$PLATFORM"

  symlinks:relink:
    desc: Remove all symlinks and recreate them (idempotent)
    cmds:
      - |
        export TERM=${TERM:-xterm}
        source "{{.DOTFILES_DIR}}/platforms/common/shell/formatting.sh"
        print_section "Relinking symlinks" "cyan"

        # Detect platform
        if [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        else
          echo "Unknown platform"
          exit 1
        fi

        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks relink "$PLATFORM"

  symlinks:check:
    desc: Verify all symlinks are correct
    cmds:
      - |
        # Detect platform
        if [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        else
          echo "Unknown platform"
          exit 1
        fi

        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks check "$PLATFORM"

  symlinks:show:
    desc: Show all configured symlinks
    cmds:
      - |
        # Detect platform
        if [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        else
          echo "Unknown platform"
          exit 1
        fi

        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks show "$PLATFORM"

  symlinks:unlink:
    desc: Remove all symlinks
    cmds:
      - |
        # Detect platform
        if [ "$(uname)" = "Darwin" ]; then
          PLATFORM="macos"
        elif grep -q "Microsoft" /proc/version 2>/dev/null || grep -q "WSL" /proc/version 2>/dev/null; then
          PLATFORM="wsl"
        elif [ -f /etc/arch-release ]; then
          PLATFORM="arch"
        else
          echo "Unknown platform"
          exit 1
        fi

        cd "{{.DOTFILES_DIR}}/management/symlinks" && uv run symlinks unlink "$PLATFORM"

  # ================================================================
  # DOCUMENTATION
  # ================================================================

  docs:serve:
    desc: Serve documentation site locally
    cmds:
      - cd docs && mkdocs serve

  docs:build:
    desc: Build documentation site
    cmds:
      - cd docs && mkdocs build

  docs:deploy:
    desc: Deploy documentation to GitHub Pages
    cmds:
      - cd docs && mkdocs gh-deploy --force

  # ================================================================
  # UPDATE COMMANDS
  # ================================================================

  update:
    desc: Update all packages (auto-detect platform)
    cmds:
      - bash update.sh {{.CLI_ARGS}}
