version: '3'

vars:
  DOTFILES_DIR:
    sh: pwd
  PLATFORM:
    sh: |
      if [ -f "$HOME/.env" ]; then
        source "$HOME/.env" && echo "$PLATFORM"
      elif [ "$(uname)" = "Darwin" ]; then
        echo "macos"
      else
        echo "linux"
      fi

includes:
  brew:
    taskfile: ./management/taskfiles/brew.yml
    optional: true
  nvm:
    taskfile: ./management/taskfiles/nvm.yml
    optional: true
  npm:
    taskfile: ./management/taskfiles/npm.yml
    optional: true
  uv:
    taskfile: ./management/taskfiles/uv.yml
    optional: true
  shell:
    taskfile: ./management/taskfiles/shell.yml
    optional: true
  symlinks:
    taskfile: ./management/taskfiles/symlinks.yml
    optional: true
  docs:
    taskfile: ./management/taskfiles/docs.yml
    optional: true
  macos:
    taskfile: ./management/taskfiles/macos.yml
    optional: true
  wsl:
    taskfile: ./management/taskfiles/wsl.yml
    optional: true
  arch:
    taskfile: ./management/taskfiles/arch.yml
    optional: true

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Auto-detect platform and install dotfiles
    silent: true
    cmds:
      - |
        case "{{.PLATFORM}}" in
          macos)
            echo "Detected macOS platform"
            task install-macos
            ;;
          linux)
            if grep -q "Microsoft" /proc/version 2>/dev/null; then
              echo "Detected WSL Ubuntu"
              task install-wsl
            elif [ -f /etc/arch-release ]; then
              echo "Detected Arch Linux"
              task install-arch
            else
              echo "Unknown Linux distribution"
              exit 1
            fi
            ;;
          *)
            echo "Unknown platform: {{.PLATFORM}}"
            exit 1
            ;;
        esac

  install-macos:
    desc: Full macOS installation
    silent: true
    cmds:
      - echo "Starting macOS dotfiles installation..."
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 1: System Tools (Homebrew)"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: macos:install-homebrew
      - task: macos:install-xcode-tools
      - task: brew:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 2: GitHub Release Tools"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: macos:install-go
      - task: macos:install-fzf
      - task: macos:install-neovim
      - task: macos:install-lazygit
      - task: macos:install-yazi
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 3: Rust/Cargo Tools"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: macos:install-rust
      - task: macos:install-cargo-tools
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 4: Language Package Managers"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: nvm:install
      - task: npm:install
      - task: uv:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 5: Shell Configuration"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: shell:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 6: Custom Go Applications"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - cd apps/common/sess && task install
      - cd apps/common/toolbox && task install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 7: Symlinking Dotfiles"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: symlinks:link
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 8: Theme System"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - bash -c 'source "$HOME/.cargo/env" && tinty install'
      - bash -c 'source "$HOME/.cargo/env" && tinty sync'
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " macOS Installation Complete!"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - echo ""
      - 'echo "Next steps:"'
      - 'echo "  1. Restart your terminal"'
      - 'echo "  2. Run ''task --list'' to see available commands"'
      - 'echo "  3. Run ''tools list'' to see installed tools"'
      - 'echo "  4. Run ''theme-sync current'' to see current theme"'
      - echo ""

  install-wsl:
    desc: Full WSL Ubuntu installation
    silent: true
    cmds:
      - echo "Starting WSL Ubuntu dotfiles installation..."
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 1: System Packages (apt)"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: wsl:install-packages
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 2: GitHub Release Tools"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: wsl:install-yq
      - task: wsl:install-go
      - task: wsl:install-fzf
      - task: wsl:install-neovim
      - task: wsl:install-lazygit
      - task: wsl:install-yazi
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 3: Rust/Cargo Tools"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: wsl:install-rust
      - task: wsl:install-cargo-tools
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 4: Language Package Managers"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: nvm:install
      - task: npm:install
      - task: wsl:install-uv
      - task: uv:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 5: Shell Configuration"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: shell:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 6: Custom Go Applications"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - cd apps/common/sess && task install
      - cd apps/common/toolbox && task install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 7: Symlinking Dotfiles"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: symlinks:link
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 8: Theme System"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - bash -c 'source "$HOME/.cargo/env" && tinty install'
      - bash -c 'source "$HOME/.cargo/env" && tinty sync'
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 9: Plugin Installation"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: wsl:install-tpm
      - task: wsl:install-tmux-plugins
      - task: wsl:install-nvim-plugins
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " WSL Ubuntu Installation Complete!"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - echo ""
      - 'echo "Next steps:"'
      - 'echo "  1. Restart your terminal (or logout/login for shell change)"'
      - 'echo "  2. Run ''task --list'' to see available commands"'
      - 'echo "  3. Run ''tools list'' to see installed tools"'
      - 'echo "  4. Run ''theme-sync current'' to see current theme"'
      - echo ""

  install-arch:
    desc: Full Arch Linux installation
    silent: true
    cmds:
      - echo "Starting Arch Linux dotfiles installation..."
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 1: System Packages (pacman)"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: arch:install-packages
      - task: arch:install-aur-helper
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 2: GitHub Release Tools"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: arch:install-go
      - task: arch:install-fzf
      - task: arch:install-neovim
      - task: arch:install-lazygit
      - task: arch:install-yazi
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 3: Rust/Cargo Tools"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: arch:install-rust
      - task: arch:install-cargo-tools
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 4: Language Package Managers"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: nvm:install
      - task: npm:install
      - task: uv:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 5: Shell Configuration"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: shell:install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 6: Custom Go Applications"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - cd apps/common/sess && task install
      - cd apps/common/toolbox && task install
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 7: Symlinking Dotfiles"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: symlinks:link
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 8: Theme System"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - bash -c 'source "$HOME/.cargo/env" && tinty install'
      - bash -c 'source "$HOME/.cargo/env" && tinty sync'
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Phase 9: System Configuration"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - task: arch:configure
      - echo ""
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - 'echo " Arch Linux Installation Complete!"'
      - 'echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"'
      - echo ""
      - 'echo "Next steps:"'
      - 'echo "  1. Restart your terminal"'
      - 'echo "  2. Run ''task --list'' to see available commands"'
      - 'echo "  3. Run ''tools list'' to see installed tools"'
      - 'echo "  4. Run ''theme-sync current'' to see current theme"'
      - echo ""
