#!/usr/bin/env bash
# ================================================================
# Sync Shell Files to Windows Git Bash
# ================================================================
# Copies shell code files from WSL to Windows Git Bash, and writes the .bashrc
# that loads them. Run with: task windows:sync (from WSL)
#
# The file list lives in SHELL_FILES below, which is both the copy manifest and
# the load order the generated .bashrc walks.
#
# Note: Binary tools are installed by 'task windows:setup'
# ================================================================

set -euo pipefail

DOTFILES_DIR="${DOTFILES_DIR:-$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)}"

# Check if we're in WSL
is_wsl() {
  grep -qE "Microsoft|WSL" /proc/version 2>/dev/null
}

# Find Windows user home directory
get_windows_home() {
  local win_user
  win_user=$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n')
  if [[ -n "$win_user" ]]; then
    echo "/mnt/c/Users/$win_user"
  fi
}

# Load order, and the copy manifest. Dependencies first: formatting.sh needs
# colors.sh, prompt.bash needs prompt-lib.sh, and windows.sh comes after the
# shared files so its overrides win.
SHELL_FILES=(
  colors.sh
  formatting.sh
  prompt-lib.sh
  functions.sh
  aliases.sh
  wsl.sh
  windows.sh
  prompt.bash
)

# Where each file comes from. The repo splits them across configs/ and the
# coordinate overlays under shell/; on the Windows side they are siblings in one
# directory, because Git Bash is not a machine this repo deploys to and has no
# coordinates of its own.
shell_file_source() {
  case "$1" in
    colors.sh | formatting.sh | prompt-lib.sh | prompt.bash)
      echo "$DOTFILES_DIR/configs/common/.local/shell/$1"
      ;;
    wsl.sh) echo "$DOTFILES_DIR/shell/host/wsl/$1" ;;
    windows.sh) echo "$DOTFILES_DIR/shell/git-bash/$1" ;;
    *) echo "$DOTFILES_DIR/shell/common/$1" ;;
  esac
}

stage_shell_files() {
  local dest="$1"
  local f src

  mkdir -p "$dest"

  for f in "${SHELL_FILES[@]}"; do
    src=$(shell_file_source "$f")
    if [[ -f "$src" ]]; then
      cp "$src" "$dest/"
      echo "  Copied: $f"
    else
      echo "  WARNING: $f not found at $src"
    fi
  done

  # Left behind by the generator this replaced; nothing sources it now.
  rm -f "$dest/combined.sh"
}

# The machine-local overlay, staged from the deployed ~/.local/shell rather than
# from the repo — it exists nowhere in this clone by design, holding shell code
# that must not be committed (employer hostnames and the like). This is the only
# place both sides can see it.
#
# Nothing is removed first: an rm would delete the Windows side's only copy of a
# file the repo cannot regenerate.
stage_local_file() {
  local dest="$1"
  local src="${2:-$HOME/.local/shell/local.sh}"

  [[ -f "$src" ]] || return 0

  # Destination named explicitly, not left to the source basename: the generated
  # .bashrc sources local.sh literally, so the name is part of the contract.
  mkdir -p "$dest"
  cp "$src" "$dest/local.sh"
  echo "  Copied: local.sh"
}

write_bashrc() {
  local win_home="$1"

  {
    cat <<'BASHRC_HEAD'
# shellcheck shell=bash
# shellcheck disable=SC1090,SC1091
# Auto-generated by sync-windows-shell.sh - do not edit
# Regenerate with: task windows:sync (from WSL)

# Larger, deduplicated history with timestamps. erasedups makes fzf history search far more useful.
HISTSIZE=100000
HISTFILESIZE=100000
HISTCONTROL=ignoreboth:erasedups
HISTTIMEFORMAT="%F %T "
shopt -s histappend cmdhist

# Navigation niceties: typo-tolerant cd, recursive ** globbing, redetect terminal size after resize
shopt -s autocd cdspell dirspell globstar checkwinsize

# Shell tool binaries (eza, rg, fd, fzf, ...) land here via `task windows:setup`
# or an offline bundle. Git Bash auto-adds ~/bin but not ~/.local/bin, so set it
# explicitly and ahead of the zoxide/fzf init below, which probe for the binaries.
export PATH="$HOME/.local/bin:$PATH"

[[ -f "$HOME/.env" ]] && source "$HOME/.env"

# The libraries resolve each other through SHELL_DIR, so it precedes the load
# below. There is no PLATFORM here: the files are named in SHELL_FILES rather
# than found by a coordinate, which is what makes this side work without the
# machine declaration the fleet reads its overlays from.
export SHELL_DIR="$HOME/.local/shell"

# One source per file, in dependency order. These were concatenated into a
# generated combined.sh until a syntax error partway through cost every alias
# and function after it, leaving no working shell to debug from. Sourced
# separately, a broken file costs only itself and names itself on the way out.
# The concatenation was for startup time and did not buy any: measured, it saved
# ~0.1ms of file opens against a ~60ms startup dominated by the subprocesses
# these files spawn, which one file versus eight does nothing about.
BASHRC_HEAD

    printf 'SHELL_FILES=(\n'
    printf '  %s\n' "${SHELL_FILES[@]}"
    printf ')\n'

    cat <<'BASHRC_TAIL'
for shell_file in "${SHELL_FILES[@]}"; do
  [[ -r "$SHELL_DIR/$shell_file" ]] || continue
  source "$SHELL_DIR/$shell_file" || echo "shell: $shell_file failed to load" >&2
done
unset shell_file SHELL_FILES

# Machine-local overlay last, so it can build on what the platform files exported.
[[ -r "$SHELL_DIR/local.sh" ]] && source "$SHELL_DIR/local.sh"

command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init bash)"
command -v fzf >/dev/null 2>&1 && eval "$(fzf --bash)"
BASHRC_TAIL
  } >"$win_home/.bashrc"
}

main() {
  # Skip if not in WSL
  if ! is_wsl; then
    echo "Not in WSL - skipping Windows shell sync"
    return 0
  fi

  local win_home
  win_home=$(get_windows_home)
  if [[ -z "$win_home" ]] || [[ ! -d "$win_home" ]]; then
    echo "Could not determine Windows home directory - skipping sync"
    return 0
  fi

  local win_shell_dir="$win_home/.local/shell"
  local shared_gitconfig="$DOTFILES_DIR/configs/common/.config/git/common.gitconfig"

  echo "Syncing shell files to Windows Git Bash..."
  echo "  Windows home: $win_home"
  echo "  Target: $win_shell_dir"

  mkdir -p "$win_home/.config/git"

  stage_shell_files "$win_shell_dir"
  stage_local_file "$win_shell_dir"

  write_bashrc "$win_home"
  echo "  Wrote: .bashrc"

  # Git for Windows reads ~/.config/git/config natively, so this needs no
  # include wiring on the Windows side. The Windows ~/.gitconfig is left alone:
  # it carries that machine's identity, which this repo never ships.
  cp "$shared_gitconfig" "$win_home/.config/git/config"
  echo "  Copied: .config/git/config"

  # Reuse the comprehensive readline config used on Mac/Linux:
  # vi mode, case-insensitive + colored completion, Shift-Tab cycling, UTF-8, history search.
  cp "$DOTFILES_DIR/configs/common/.config/readline/inputrc" "$win_home/.inputrc"
  echo "  Copied: .inputrc"

  echo "Windows shell sync complete."
}

# Sourced by tests/shell/test_windows_shell_sync_sh.py, which calls the
# generation functions directly rather than reimplementing the file list.
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  main "$@"
fi
