[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "dev"
path = "~/dev"

[[session]]
name = "ichrisbirch"
path = "~/webapps/ichrisbirch"
