###################################################################################
########### ------------------------- SYSTEM  ------------------------- ###########
###################################################################################

start-at-login = true
after-startup-command = []

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 50

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 0
outer.bottom = 0
outer.top = 0
outer.right = 0


###################################################################################
########## ------------------------- MAIN MODE ------------------------- ##########
###################################################################################

# 'main' binding mode must be always presented
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#                   sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

cmd-h = []     # disable hide application
cmd-alt-h = [] # disable hide others

# You can uncomment the following lines to open up terminal with alt + enter shortcut
alt-enter = '''exec-and-forget osascript -e '
tell application "Wezterm"
    do script
    activate
end tell'
'''

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-tab = 'workspace-back-and-forth'

ctrl-alt-shift-semicolon = 'mode alt'
alt-shift-semicolon = 'mode service'

###################################################################################
########## ------------------------- ALT MODE ------------------------- ###########
###################################################################################

[mode.alt.binding]
esc = ['mode main']

quote = 'resize smart -50'
backslash = 'resize smart +50'

# Workspace navigation (exits to main mode after navigation)
i = ['workspace I', 'mode main'] # ichrisbirch - terminal
c = ['workspace C', 'mode main'] # ichrisbirch - editor
b = ['workspace B', 'mode main'] # ichrisbirch - panel

t = ['workspace T', 'mode main'] # project - terminal
w = ['workspace W', 'mode main'] # project - editor
a = ['workspace A', 'mode main'] # project - panel

x = ['workspace X', 'mode main'] # misc
y = ['workspace Y', 'mode main'] # misc
z = ['workspace Z', 'mode main'] # misc

d = ['workspace D', 'mode main'] # dotfiles
u = ['workspace U', 'mode main'] # university
q = ['workspace Q', 'mode main'] # quick temporary

e = ['workspace E', 'mode main'] # email
m = ['workspace M', 'mode main'] # music
s = ['workspace S', 'mode main'] # social

# Move node to workspace (exits to main mode after moving)
shift-i = ['move-node-to-workspace I', 'mode main']
shift-c = ['move-node-to-workspace C', 'mode main']
shift-b = ['move-node-to-workspace B', 'mode main']

shift-t = ['move-node-to-workspace T', 'mode main']
shift-w = ['move-node-to-workspace W', 'mode main']
shift-a = ['move-node-to-workspace A', 'mode main']

shift-x = ['move-node-to-workspace X', 'mode main']
shift-y = ['move-node-to-workspace Y', 'mode main']
shift-z = ['move-node-to-workspace Z', 'mode main']

shift-d = ['move-node-to-workspace D', 'mode main']
shift-u = ['move-node-to-workspace U', 'mode main']
shift-q = ['move-node-to-workspace Q', 'mode main']

shift-e = ['move-node-to-workspace E', 'mode main']
shift-m = ['move-node-to-workspace M', 'mode main']
shift-s = ['move-node-to-workspace S', 'mode main']

shift-h = ['join-with left', 'mode main']
shift-j = ['join-with down', 'mode main']
shift-k = ['join-with up', 'mode main']
shift-l = ['join-with right', 'mode main']

alt-h = ['focus-monitor left', 'mode main']
alt-l = ['focus-monitor right', 'mode main']

alt-shift-h = ['move-workspace-to-monitor left', 'mode main']
alt-shift-l = ['move-workspace-to-monitor right', 'mode main']

slash = 'layout tiles horizontal vertical'
comma = 'layout accordion horizontal vertical'

# [workspace-to-monitor-force-assignment]
# i = ['2']
# c = 'main'
# b = ['1']
# t = ['2']
# w = 'main'
# a = ['1']
# z = ['2']
# x = 'main'
# l = 'main'
# q = 'main'
# e = ['1']
# m = ['1']
# s = 'main'

###################################################################################
######## ------------------------- SERVICE MODE ------------------------- #########
###################################################################################


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']                # reset layout
f = ['layout floating tiling', 'mode main']                # Toggle floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']
