
[mgr]
ratio = [1, 3, 4]
show_hidden = true

[preview]
max_width = 1200
max_height = 1800

[opener]
edit = [
  { run = 'cd "${YAZI_LAUNCH_DIR:-.}" && nvim "$@"', block = true, for = "unix" },
]
play = [
  { run = 'mpv --force-window %s', orphan = true, for = "unix" },
  { run = 'mpv --force-window %s', orphan = true, for = "windows" },
  { run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]

[[plugin.prepend_fetchers]]
id    = "git"
group = "git"
url   = "*"
run   = "git"

[[plugin.prepend_fetchers]]
id    = "git"
group = "git"
url   = "*/"
run   = "git"

[[plugin.prepend_previewers]]
url = "*.ipynb"
run = "nbpreview"
