"""What a `check` leaves behind for something that is not watching it.

Two files, and the split is the whole design. `status.json` is the document —
every resource's verdict and when it was measured — for a caller that wants to
reason about the machine. `nudge` is one line of human text, present only when
there is something a person should act on.

Two rather than one because of who reads them. The nudge is read by a **shell
snippet at every prompt**, and JSON parsing in zsh means `jq`, which means a
subprocess per shell — the exact cost `.zshrc`'s completion caching exists to
avoid. A one-line file is `$(<file)`, which zsh reads with no fork at all.

**It fires on Issues, not on drift.** Drift is the normal state of a machine
between applies; nudging about it every prompt would train the nudge away inside
a week. An Issue is something wrong — a checker that could not run, a declaration
that will not parse — and those are rare enough to be worth interrupting for.

Written by every `check`, not only the scheduled one, so an interactive check
also refreshes what the next shell reports. That is what stops the nudge
outliving the problem it describes.
"""

from __future__ import annotations

import datetime as dt
import json
from collections.abc import Sequence

from dotfiles import paths
from dotfiles.reconcile import ResourceResult
from dotfiles.reconcile import ResourceVerdict


def record(results: Sequence[ResourceResult], machine: str, when: dt.datetime) -> None:
    """Write both files, or neither. A check must never fail because of this.

    The state directory is on Syncthing for the fleet and absent on a fresh
    machine, and neither is a reason for `dotfiles check` to exit non-zero — it
    answered the question it was asked.
    """
    try:
        paths.STATE_HOME.mkdir(parents=True, exist_ok=True)
        paths.STATUS_FILE.write_text(json.dumps(document(results, machine, when), indent=2) + '\n')
        _write_nudge(results)
    except OSError:
        return


def document(results: Sequence[ResourceResult], machine: str, when: dt.datetime, verb: str = 'check') -> dict[str, object]:
    """The versioned interchange document.

    Versioned because it crosses machines: the work box's output is what decides
    what the fleet builds into its next offline bundle, and an unversioned
    document breaks silently when the two ends disagree about its shape.

    `verb` names which question produced it. `plan` and `check` measure the same
    machine and keep different findings, so two documents of one shape would
    otherwise be indistinguishable — and the bundle builder wants the plan's rows
    while the nudge wants the check's.
    """
    return {
        'version': 1,
        'verb': verb,
        'machine': machine,
        'checked': when.isoformat(),
        'verdict': _worst(results),
        'resources': [result.as_dict() for result in results],
    }


def _worst(results: Sequence[ResourceResult]) -> str:
    verdicts = {result.verdict for result in results}
    if ResourceVerdict.ISSUE in verdicts:
        return str(ResourceVerdict.ISSUE)
    return str(ResourceVerdict.DRIFT if ResourceVerdict.DRIFT in verdicts else ResourceVerdict.CONVERGED)


def _write_nudge(results: Sequence[ResourceResult]) -> None:
    """One line, or the file removed. Removed rather than emptied, because the
    shell tests for a non-empty file and a stale empty one is a file whose mtime
    keeps saying the check ran."""
    issues = [result for result in results if result.verdict is ResourceVerdict.ISSUE]
    if not issues:
        paths.NUDGE_FILE.unlink(missing_ok=True)
        return

    named = ', '.join(result.address for result in issues)
    paths.NUDGE_FILE.write_text(f'dotfiles: {len(issues)} resource(s) need attention ({named}) — run: dotfiles check\n')


SNIPPETS = {
    'zsh': """\
# Generated by `dotfiles shell-init zsh`; cached by cache_eval in .zshrc.
() {
  # Suffixed because the fleet shares this directory: an unsuffixed nudge would
  # be whichever machine checked last, reporting its failure on every other one.
  #
  # $MACHINE and no fallback. It comes from ~/.env, which .zshrc sources before
  # this, and a machine without one has no nudge file under any name — so the
  # empty-test below is already the right answer and a `hostname` fork would buy
  # nothing but a subprocess on every prompt.
  local nudge=${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles/nudge-$MACHINE
  [[ -s $nudge ]] || return 0

  # zsh/stat and zsh/datetime are builtin modules, so the whole check costs no
  # subprocess: the point of a startup nudge is that it is invisible when there
  # is nothing to say, and a fork per prompt is not invisible.
  zmodload -F zsh/stat b:zstat 2>/dev/null || return 0
  zmodload zsh/datetime 2>/dev/null || return 0

  local -a stamp
  zstat -A stamp +mtime -- $nudge 2>/dev/null || return 0
  # A stale nudge is worse than none: a timer that stopped running would leave a
  # week-old warning on screen with nothing to say it had stopped being true.
  (( EPOCHSECONDS - stamp[1] < %(max_age)d )) || return 0

  print -r -- $(<$nudge)
}
""",
    'bash': """\
# Generated by `dotfiles shell-init bash`.
__dotfiles_nudge() {
  local nudge="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles/nudge-$MACHINE"
  [ -s "$nudge" ] || return 0
  # bash has no builtin stat, so this is one subprocess per shell rather than
  # zsh's none. Accepted: bash here is a fallback shell, not the daily one.
  local age=$(( $(date +%%s) - $(stat -c %%Y "$nudge" 2>/dev/null || echo 0) ))
  [ "$age" -lt %(max_age)d ] || return 0
  cat "$nudge"
}
__dotfiles_nudge
""",
}

MAX_AGE_SECONDS = 60 * 60 * 24
"""How old the nudge may be before the shell ignores it.

A day, because the schedule runs several times a day: anything older means the
timer is not running, and a warning nobody is refreshing is a warning that has
stopped being evidence.
"""


def snippet(shell: str) -> str:
    return SNIPPETS[shell] % {'max_age': MAX_AGE_SECONDS}
