#!/usr/bin/env bash
# ================================================================
# Sync Shell Files to Windows Git Bash
# ================================================================
# Copies shell configuration files from WSL to Windows Git Bash.
# Called automatically by 'task shell:build' when in WSL.
#
# Copies these files to Windows ~/.local/shell/:
#   - colors.sh (from repo - no dependencies)
#   - formatting.sh (from repo - uses colors.sh)
#   - prompt-lib.sh (from repo - shared prompt utilities)
#   - aliases.sh (built by shell:build)
#   - functions.sh (built by shell:build)
#   - prompt.bash (from repo - bash prompt)
#
# Also generates combined.sh that sources all files in order,
# with Windows-specific overrides at the end (e.g., alias open='start').
#
# Note: Binary tools are installed by 'task windows:setup'
# ================================================================

set -euo pipefail

DOTFILES_DIR="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"

# Check if we're in WSL
is_wsl() {
  grep -qE "Microsoft|WSL" /proc/version 2>/dev/null
}

# Find Windows user home directory
get_windows_home() {
  local win_user
  win_user=$(cmd.exe /c "echo %USERNAME%" 2>/dev/null | tr -d '\r\n')
  if [[ -n "$win_user" ]]; then
    echo "/mnt/c/Users/$win_user"
  fi
}

main() {
  # Skip if not in WSL
  if ! is_wsl; then
    echo "Not in WSL - skipping Windows shell sync"
    return 0
  fi

  local win_home
  win_home=$(get_windows_home)
  if [[ -z "$win_home" ]] || [[ ! -d "$win_home" ]]; then
    echo "Could not determine Windows home directory - skipping sync"
    return 0
  fi

  local win_shell_dir="$win_home/.local/shell"
  local repo_shell_dir="$DOTFILES_DIR/platforms/common/.local/shell"
  local wsl_shell_dir="$HOME/.local/shell"

  echo "Syncing shell files to Windows Git Bash..."
  echo "  Windows home: $win_home"
  echo "  Target: $win_shell_dir"

  # Create target directory
  mkdir -p "$win_shell_dir"

  # Copy static files from repo
  cp "$repo_shell_dir/colors.sh" "$win_shell_dir/"
  echo "  Copied: colors.sh"

  cp "$repo_shell_dir/formatting.sh" "$win_shell_dir/"
  echo "  Copied: formatting.sh"

  cp "$repo_shell_dir/prompt-lib.sh" "$win_shell_dir/"
  echo "  Copied: prompt-lib.sh"

  cp "$repo_shell_dir/prompt.bash" "$win_shell_dir/"
  echo "  Copied: prompt.bash"

  # Copy built files from WSL shell dir
  if [[ -f "$wsl_shell_dir/aliases.sh" ]]; then
    cp "$wsl_shell_dir/aliases.sh" "$win_shell_dir/"
    echo "  Copied: aliases.sh"
  else
    echo "  WARNING: aliases.sh not found in $wsl_shell_dir"
  fi

  if [[ -f "$wsl_shell_dir/functions.sh" ]]; then
    cp "$wsl_shell_dir/functions.sh" "$win_shell_dir/"
    echo "  Copied: functions.sh"
  else
    echo "  WARNING: functions.sh not found in $wsl_shell_dir"
  fi

  # Generate combined.sh with proper dependency order
  local combined_file="$win_shell_dir/combined.sh"
  {
    cat <<'EOF'
# Combined shell config for Git Bash
# Auto-generated by sync-windows-shell.sh - do not edit
# Regenerate with: task shell:build (from WSL)

# Set SHELL_DIR for formatting.sh to find colors.sh
SHELL_DIR="$HOME/.local/shell"
export SHELL_DIR

EOF

    # 1. colors.sh - no dependencies
    echo "# ================================================================"
    echo "# COLORS"
    echo "# ================================================================"
    cat "$win_shell_dir/colors.sh"
    echo ""

    # 2. formatting.sh - uses colors.sh
    echo "# ================================================================"
    echo "# FORMATTING"
    echo "# ================================================================"
    # Strip the colors.sh sourcing block (lines 19-27) since colors.sh is already included
    sed '19,27d' "$win_shell_dir/formatting.sh"
    echo ""

    # 3. prompt-lib.sh - shared prompt utilities
    echo "# ================================================================"
    echo "# PROMPT LIBRARY"
    echo "# ================================================================"
    cat "$win_shell_dir/prompt-lib.sh"
    echo ""

    # 4. aliases.sh
    if [[ -f "$win_shell_dir/aliases.sh" ]]; then
      echo "# ================================================================"
      echo "# ALIASES"
      echo "# ================================================================"
      cat "$win_shell_dir/aliases.sh"
      echo ""
    fi

    # 5. functions.sh - may source colors.sh via SHELL_DIR
    if [[ -f "$win_shell_dir/functions.sh" ]]; then
      echo "# ================================================================"
      echo "# FUNCTIONS"
      echo "# ================================================================"
      cat "$win_shell_dir/functions.sh"
      echo ""
    fi

    # 6. prompt.bash - bash prompt configuration
    echo "# ================================================================"
    echo "# BASH PROMPT"
    echo "# ================================================================"
    # Strip the prompt-lib.sh sourcing block (lines 9-14) since it's already included
    sed '9,14d' "$win_shell_dir/prompt.bash"
    echo ""

    # 7. Windows-specific overrides
    echo "# ================================================================"
    echo "# WINDOWS OVERRIDES"
    echo "# ================================================================"
    cat <<'OVERRIDES'
# macOS 'open' equivalent
alias open='start'
OVERRIDES
    echo ""

  } > "$combined_file"

  echo "  Generated: combined.sh ($(wc -l < "$combined_file") lines)"
  echo "Windows shell sync complete."
}

main "$@"
