[general]
import = ["~/.config/alacritty/themes/themes/miasma.toml"]

[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
decorations = "Buttonless"
dynamic_padding = true
opacity = 1.0
blur = true
padding = { x = 15, y = 15 }

[font]
size = 16.0
normal = { family = "SeriousShanns Nerd Font Mono" }
offset = { x = 2, y = 2 }

# size = 18.0
# normal = { family = "Terminess Nerd Font Mono" }
# offset = { x = 1, y = 1 }

[scrolling]
history = 100000
